### PR TITLE
Rename to mapFoo

### LINKED ISSUE #2: Naming?
Personally I'm not a fan of the "fooIn" names - I suspect many will have bikeshedding opinions.

I think it would behoove us to gather everyone's naming thoughts in one place - perhaps this thread - so that any decision can be made with as much confidence as possible.

### PR DESCRIPTION
**Pull request by leobalter**
@jdalton @ljharb

Closes #2

### CODE REVIEW

**Comment by leobalter** [comment]
From @jdalton 

> The name `map` makes me think of `Array#map` or `Map`.

**Comment by ljharb** [comment]
hmm - `mapKeys` makes me think it takes a callback and returns a new array. does it?

**Comment by leobalter** [comment]
no, it does not.

**Comment by ljharb** [comment]
then i'm not sure "map" is the right term. a map operation produces a mapped copy.

**Comment by leobalter** [comment]
Agreed. That's why this is already closed. :)

**Pull request closed without merging**
